[project]
name = "noessi-crawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.7.7",
    "playwright>=1.56.0",
    "httpx>=0.27.0",
    "pyyaml>=6.0",
    "fpdf2>=2.8.5",
]
